# fly.toml app configuration file generated for pdf-processor-8a350q on 2025-02-15T01:04:13Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pdf-processor-8a350q'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
